/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    colors: {
      surface: 'var(--color-surface)',
      'surface-dim': 'var(--color-surface-dim)',
      'surface-bright': 'var(--color-surface-bright)',
      'surface-container-lowest': 'var(--color-surface-container-lowest)',
      'surface-container-low': 'var(--color-surface-container-low)',
      'surface-container': 'var(--color-surface-container)',
      'surface-container-high': 'var(--color-surface-container-high)',
      'surface-container-highest': 'var(--color-surface-container-highest)',
      'on-surface': 'var(--color-on-surface)',
      'on-surface-variant': 'var(--color-on-surface-variant)',
      outline: 'var(--color-outline)',
      'outline-variant': 'var(--color-outline-variant)',
      'text-mid': 'var(--color-text-mid)',
      'text-faint': 'var(--color-text-faint)',
      primary: 'var(--color-primary)',
      'on-primary': 'var(--color-on-primary)',
      'primary-container': 'var(--color-primary-container)',
      'on-primary-container': 'var(--color-on-primary-container)',
      accent: 'var(--color-accent)',
      'accent-light': 'var(--color-accent-light)',
      'accent-dark': 'var(--color-accent-dark)',
      'bg-warm': 'var(--color-bg-warm)',
      'bg-card': 'var(--color-bg-card)',
      'bg-ink': 'var(--color-bg-ink)',
      border: 'var(--color-border)',
      'border-strong': 'var(--color-border-strong)',
      'border-subtle': 'var(--color-border-subtle)',
      'status-unfair': 'var(--color-status-unfair)',
      'status-unfair-bg': 'var(--color-status-unfair-bg)',
      'status-unfair-border': 'var(--color-status-unfair-border)',
      'status-borderline': 'var(--color-status-borderline)',
      'status-borderline-bg': 'var(--color-status-borderline-bg)',
      'status-borderline-border': 'var(--color-status-borderline-border)',
      'status-fair': 'var(--color-status-fair)',
      'status-fair-bg': 'var(--color-status-fair-bg)',
      'status-fair-border': 'var(--color-status-fair-border)',
      'role-sensitive': 'var(--color-role-sensitive)',
      'role-sensitive-bg': 'var(--color-role-sensitive-bg)',
      'role-target': 'var(--color-role-target)',
      'role-target-bg': 'var(--color-role-target-bg)',
      'role-proxy': 'var(--color-role-proxy)',
      'role-proxy-bg': 'var(--color-role-proxy-bg)',
      'role-neutral': 'var(--color-role-neutral)',
      'role-neutral-bg': 'var(--color-role-neutral-bg)',
    },
  },
};
